server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /oauth2 {
        proxy_pass 192.168.5.2:8090;
    }

    location /users {
        proxy_pass 192.168.5.2:8090;
    }

    location /scim2 {
        proxy_pass 192.168.5.2:8090;
    }

    location /flow {
        proxy_pass 192.168.5.2:8090;
    }

    location /.well-known {
        proxy_pass 192.168.5.2:8090;
    }

    location /t {
        proxy_pass 192.168.5.2:8090;
    }

    location /gate {
        proxy_pass 192.168.5.2:8090;
    }
}